### ISSUE TITLE
Escenario - Perforación de Escenario ----ERROR

### ISSUE THREAD

**Issue by pereirajangel** [Spontecorp-CA/Sismon_6#103]
Intentaba hacer el proceso de perforación del escenario.

mar 30, 2016 3:11:10 PM com.sismon.vista.escenario.PerforacionEscenariolIF procesarButtonActionPerformed
GRAVE: null
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at javax.swing.SwingWorker.get(SwingWorker.java:602)
	at com.sismon.vista.escenario.PerforacionEscenariolIF.procesarButtonActionPerformed(PerforacionEscenariolIF.java:544)
	at com.sismon.vista.escenario.PerforacionEscenariolIF.access$700(PerforacionEscenariolIF.java:36)
	at com.sismon.vista.escenario.PerforacionEscenariolIF$6.actionPerformed(PerforacionEscenariolIF.java:424)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)

[Error-Perforacion-Escenario.txt](https://github.com/Spontecorp-CA/Sismon_6/files/196319/Error-Perforacion-Escenario.txt)

**Comment by jgcastillo** [comment]
Se modificó el tamaño del arreglo de carga de los datos y se asigno la parte de los días, dias activos y diás inactivos
